

include ':app'
include ':uniplugin_module'
include ':uniplugin_component'
//include ':uniplugin_richalert'
include ':uts-toast'
include 'zimkit'
include(":voiceroomkit-ui-base")
include(":voiceroomkit-ui")
include(":voiceroomkit")
include(":entertainment:entertainment-common")
include(":ordersong")